# yaml-language-server: $schema=https://unpkg.com/@sveltia/cms/schema/sveltia-cms.json

backend:
  name: github
  repo: F43ser/felix-eickelmann.de

media_folder: /static/media
public_folder: /static/media/public

collections:
  - name: posts
    label: Posts
    label_singular: Post
    folder: /content/posts
    fields:
      - { label: Title, name: title, widget: string }
      - { label: Date, name: date, widget: datetime, type: date }
      - { label: Body, name: body, widget: richtext }
  - name: pages
    label: Pages
    label_singular: Page
    folder: /content/pages
    fields:
      - { label: Title, name: title, widget: string }
      - { label: Body, name: body, widget: richtext }